version: '3.3'

#Docker networks
networks:
  hospital-network:
    driver: bridge

#Docker volumns
volumes:
  dbdata:
    driver: local

services:
  php:
    container_name: HOSPITAL_PHP
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - hospital-network

  app:
    image: nginx:alpine
    container_name: HOSPITAL_API
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    networks:
      - hospital-network

  db:
    image: mysql
    container_name: HOSPITAL_DB
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "hospital"
      MYSQL_ROOT_PASSWORD: "root"
      SERICE_TAGS: "local"
      SERIVE_NAME: "mysql"
    networks:
      - hospital-network
    command: 
      - --innodb_strict_mode=0
      - --innodb-log-buffer-size=256M
      - --innodb_redo_log_capacity=2147483648
    volumes:
      - dbdata:/var/lib/mysql/
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: HOSPITAL_PHPMYADMIN
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - hospital-network

  mailhog:
    image: mailhog/mailhog
    container_name: HOSPITAL_MAILHOG
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8082:8025
    networks:
      - hospital-network
