<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UpdateInTestsColumnsOne extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->date('result_date_10')->nullable();
            $table->text('result_cyc_day_10')->nullable();
            $table->text('result_stm_day_10')->nullable();
            $table->text('result_end_10')->nullable();
            $table->text('result_rafc_10')->nullable();
            $table->text('result_lafc_10')->nullable();
            $table->text('result_stimulation_10')->nullable();
            $table->text('result_misc_10')->nullable();
            $table->date('result_date_11')->nullable();
            $table->text('result_cyc_day_11')->nullable();
            $table->text('result_stm_day_11')->nullable();
            $table->text('result_end_11')->nullable();
            $table->text('result_rafc_11')->nullable();
            $table->text('result_lafc_11')->nullable();
            $table->text('result_stimulation_11')->nullable();
            $table->text('result_misc_11')->nullable();
            $table->date('result_date_12')->nullable();
            $table->text('result_cyc_day_12')->nullable();
            $table->text('result_stm_day_12')->nullable();
            $table->text('result_end_12')->nullable();
            $table->text('result_rafc_12')->nullable();
            $table->text('result_lafc_12')->nullable();
            $table->text('result_stimulation_12')->nullable();
            $table->text('result_misc_12')->nullable();
            $table->date('result_date_13')->nullable();
            $table->text('result_cyc_day_13')->nullable();
            $table->text('result_stm_day_13')->nullable();
            $table->text('result_end_13')->nullable();
            $table->text('result_rafc_13')->nullable();
            $table->text('result_lafc_13')->nullable();
            $table->text('result_stimulation_13')->nullable();
            $table->text('result_misc_13')->nullable();
            $table->date('result_date_14')->nullable();
            $table->text('result_cyc_day_14')->nullable();
            $table->text('result_stm_day_14')->nullable();
            $table->text('result_end_14')->nullable();
            $table->text('result_rafc_14')->nullable();
            $table->text('result_lafc_14')->nullable();
            $table->text('result_stimulation_14')->nullable();
            $table->text('result_misc_14')->nullable();
            $table->date('result_date_15')->nullable();
            $table->text('result_cyc_day_15')->nullable();
            $table->text('result_stm_day_15')->nullable();
            $table->text('result_end_15')->nullable();
            $table->text('result_rafc_15')->nullable();
            $table->text('result_lafc_15')->nullable();
            $table->text('result_stimulation_15')->nullable();
            $table->text('result_misc_15')->nullable();
            $table->date('result_date_16')->nullable();
            $table->text('result_cyc_day_16')->nullable();
            $table->text('result_stm_day_16')->nullable();
            $table->text('result_end_16')->nullable();
            $table->text('result_rafc_16')->nullable();
            $table->text('result_lafc_16')->nullable();
            $table->text('result_stimulation_16')->nullable();
            $table->text('result_misc_16')->nullable();
            $table->text('result_hcg')->nullable();
            $table->text('result_datetime1')->nullable();
            $table->text('result_opu')->nullable();
            $table->text('result_datetime2')->nullable();
            $table->text('result_coc')->nullable();
            $table->text('result_gv')->nullable();
            $table->text('result_m1')->nullable();
            $table->text('result_m2')->nullable();
            $table->text('result_ivf')->nullable();
            $table->text('result_icsi')->nullable();
            $table->text('result_et1')->nullable();
            $table->text('result_cryo')->nullable();
            $table->text('result_et2')->nullable();
            $table->text('result_datetime3')->nullable();
            $table->text('result_details')->nullable();
            $table->text('result_vp')->nullable();
            $table->text('result_eudate')->nullable();
            $table->text('result_bhcg')->nullable();
            $table->text('result_semen_cryo')->nullable();
            $table->text('result_afh')->nullable();
            $table->text('result_antifungal')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->dropColumn('result_date_10');
            $table->dropColumn('result_cyc_day_10');
            $table->dropColumn('result_stm_day_10');
            $table->dropColumn('result_end_10');
            $table->dropColumn('result_rafc_10');
            $table->dropColumn('result_lafc_10');
            $table->dropColumn('result_stimulation_10');
            $table->dropColumn('result_misc_10');
            $table->dropColumn('result_date_11');
            $table->dropColumn('result_cyc_day_11');
            $table->dropColumn('result_stm_day_11');
            $table->dropColumn('result_end_11');
            $table->dropColumn('result_rafc_11');
            $table->dropColumn('result_lafc_11');
            $table->dropColumn('result_stimulation_11');
            $table->dropColumn('result_misc_11');
            $table->dropColumn('result_date_12');
            $table->dropColumn('result_cyc_day_12');
            $table->dropColumn('result_stm_day_12');
            $table->dropColumn('result_end_12');
            $table->dropColumn('result_rafc_12');
            $table->dropColumn('result_lafc_12');
            $table->dropColumn('result_stimulation_12');
            $table->dropColumn('result_misc_12');
            $table->dropColumn('result_date_13');
            $table->dropColumn('result_cyc_day_13');
            $table->dropColumn('result_stm_day_13');
            $table->dropColumn('result_end_13');
            $table->dropColumn('result_rafc_13');
            $table->dropColumn('result_lafc_13');
            $table->dropColumn('result_stimulation_13');
            $table->dropColumn('result_misc_13');
            $table->dropColumn('result_date_14');
            $table->dropColumn('result_cyc_day_14');
            $table->dropColumn('result_stm_day_14');
            $table->dropColumn('result_end_14');
            $table->dropColumn('result_rafc_14');
            $table->dropColumn('result_lafc_14');
            $table->dropColumn('result_stimulation_14');
            $table->dropColumn('result_misc_14');
            $table->dropColumn('result_date_15');
            $table->dropColumn('result_cyc_day_15');
            $table->dropColumn('result_stm_day_15');
            $table->dropColumn('result_end_15');
            $table->dropColumn('result_rafc_15');
            $table->dropColumn('result_lafc_15');
            $table->dropColumn('result_stimulation_15');
            $table->dropColumn('result_misc_15');
            $table->dropColumn('result_date_16');
            $table->dropColumn('result_cyc_day_16');
            $table->dropColumn('result_stm_day_16');
            $table->dropColumn('result_end_16');
            $table->dropColumn('result_rafc_16');
            $table->dropColumn('result_lafc_16');
            $table->dropColumn('result_stimulation_16');
            $table->dropColumn('result_misc_16');
            $table->dropColumn('result_hcg');
            $table->dropColumn('result_datetime1');
            $table->dropColumn('result_opu');
            $table->dropColumn('result_datetime2');
            $table->dropColumn('result_coc');
            $table->dropColumn('result_gv');
            $table->dropColumn('result_m1');
            $table->dropColumn('result_m2');
            $table->dropColumn('result_ivf');
            $table->dropColumn('result_icsi');
            $table->dropColumn('result_et1');
            $table->dropColumn('result_cryo');
            $table->dropColumn('result_et2');
            $table->dropColumn('result_datetime3');
            $table->dropColumn('result_details');
            $table->dropColumn('result_vp');
            $table->dropColumn('result_eudate');
            $table->dropColumn('result_bhcg');
            $table->dropColumn('result_semen_cryo');
            $table->dropColumn('result_afh');
            $table->dropColumn('result_antifungal');
        });
    }
}
