<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UpdateInTestsColumnsFour extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->text('sperm_source_ejaculated')->nullable();
            $table->text('sperm_source_donor')->nullable();
            $table->text('sperm_source_pesa')->nullable();
            $table->text('sperm_source_cryo')->nullable();
            $table->text('sperm_source_test')->nullable();
            $table->text('sperm_source_recovery')->nullable();
            $table->text('sperm_source_whom')->nullable();
            $table->text('sperm_source_when')->nullable();
            $table->text('sperm_source_infertility_type')->nullable();
            $table->text('sperm_source_age')->nullable();
            $table->text('sperm_source_lmp')->nullable();
            $table->text('sperm_source_drd')->nullable();
            $table->text('sperm_source_et')->nullable();
            $table->text('sperm_source_ss_date_1')->nullable();
            $table->date('sperm_source_date_1')->nullable();
            $table->text('sperm_source_e2_1')->nullable();
            $table->text('sperm_source_lh_1')->nullable();
            $table->text('sperm_source_ss_date_2')->nullable();
            $table->date('sperm_source_date_2')->nullable();
            $table->text('sperm_source_e2_2')->nullable();
            $table->text('sperm_source_lh_2')->nullable();
            $table->text('sperm_source_ss_date_3')->nullable();
            $table->date('sperm_source_date_3')->nullable();
            $table->text('sperm_source_e2_3')->nullable();
            $table->text('sperm_source_lh_3')->nullable();
            $table->text('sperm_source_hcg')->nullable();
            $table->text('sperm_source_ovum')->nullable();
            $table->text('sperm_source_media_type')->nullable();
            $table->text('sperm_source_folliciles_right')->nullable();
            $table->text('sperm_source_folliciles_left')->nullable();
            $table->text('sperm_source_folliciles_total')->nullable();
            $table->text('sperm_source_ovum_right')->nullable();
            $table->text('sperm_source_ovum_left')->nullable();
            $table->text('sperm_source_ovum_pod')->nullable();
            $table->text('sperm_source_ovum_total')->nullable();
            $table->text('oocyte_quality_1_no')->nullable();
            $table->text('oocyte_quality_1_stage')->nullable();
            $table->text('oocyte_quality_2_no')->nullable();
            $table->text('oocyte_quality_2_stage')->nullable();
            $table->text('oocyte_quality_3_no')->nullable();
            $table->text('oocyte_quality_3_stage')->nullable();
            $table->text('oocyte_quality_4_no')->nullable();
            $table->text('oocyte_quality_4_stage')->nullable();
            $table->text('oocyte_quality_5_no')->nullable();
            $table->text('oocyte_quality_5_stage')->nullable();
            $table->text('oocyte_quality_6_no')->nullable();
            $table->text('oocyte_quality_6_stage')->nullable();
            $table->date('et_date_of_et')->nullable();
            $table->text('et_time_of_et')->nullable();
            $table->text('et_endometrium_t')->nullable();
            $table->text('et_cathetar')->nullable();
            $table->text('et_transfer_stage')->nullable();
            $table->text('et_embryo_transfer')->nullable();
            $table->date('bt_date_of_et')->nullable();
            $table->text('bt_time_of_et')->nullable();
            $table->text('bt_endometrium_t')->nullable();
            $table->text('bt_cathetar')->nullable();
            $table->text('bt_transfer_stage')->nullable();
            $table->text('bt_embryo_transfer')->nullable();
            $table->text('frozen_stage')->nullable();
            $table->text('frozen_blastocyst')->nullable();
            $table->text('frozen_embryo_datetime')->nullable();
            $table->text('frozen_blastocyst_datetime')->nullable();
            $table->text('frozen_straws')->nullable();
            $table->text('frozen_mark')->nullable();
            $table->text('frozen_plastic_colour')->nullable();
            $table->text('frozen_ln2')->nullable();
            $table->date('thawing_date_of_et')->nullable();
            $table->text('thawing_time_of_et')->nullable();
            $table->text('thawing_endometrium_t')->nullable();
            $table->text('thawing_cathetar')->nullable();
            $table->text('thawing_transfer_stage')->nullable();
            $table->text('thawing_embryo_transfer')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->dropColumn('sperm_source_ejaculated');
            $table->dropColumn('sperm_source_donor');
            $table->dropColumn('sperm_source_pesa');
            $table->dropColumn('sperm_source_cryo');
            $table->dropColumn('sperm_source_test');
            $table->dropColumn('sperm_source_recovery');
            $table->dropColumn('sperm_source_whom');
            $table->dropColumn('sperm_source_when');
            $table->dropColumn('sperm_source_infertility_type');
            $table->dropColumn('sperm_source_age');
            $table->dropColumn('sperm_source_lmp');
            $table->dropColumn('sperm_source_drd');
            $table->dropColumn('sperm_source_et');
            $table->dropColumn('sperm_source_ss_date_1');
            $table->dropColumn('sperm_source_date_1');
            $table->dropColumn('sperm_source_e2_1');
            $table->dropColumn('sperm_source_lh_1');
            $table->dropColumn('sperm_source_ss_date_2');
            $table->dropColumn('sperm_source_date_2');
            $table->dropColumn('sperm_source_e2_2');
            $table->dropColumn('sperm_source_lh_2');
            $table->dropColumn('sperm_source_ss_date_3');
            $table->dropColumn('sperm_source_date_3');
            $table->dropColumn('sperm_source_e2_3');
            $table->dropColumn('sperm_source_lh_3');
            $table->dropColumn('sperm_source_hcg');
            $table->dropColumn('sperm_source_ovum');
            $table->dropColumn('sperm_source_media_type');
            $table->dropColumn('sperm_source_folliciles_right');
            $table->dropColumn('sperm_source_folliciles_left');
            $table->dropColumn('sperm_source_folliciles_total');
            $table->dropColumn('sperm_source_ovum_right');
            $table->dropColumn('sperm_source_ovum_left');
            $table->dropColumn('sperm_source_ovum_pod');
            $table->dropColumn('sperm_source_ovum_total');
            $table->dropColumn('oocyte_quality_1_no');
            $table->dropColumn('oocyte_quality_1_stage');
            $table->dropColumn('oocyte_quality_2_no');
            $table->dropColumn('oocyte_quality_2_stage');
            $table->dropColumn('oocyte_quality_3_no');
            $table->dropColumn('oocyte_quality_3_stage');
            $table->dropColumn('oocyte_quality_4_no');
            $table->dropColumn('oocyte_quality_4_stage');
            $table->dropColumn('oocyte_quality_5_no');
            $table->dropColumn('oocyte_quality_5_stage');
            $table->dropColumn('oocyte_quality_6_no');
            $table->dropColumn('oocyte_quality_6_stage');
            $table->dropColumn('et_date_of_et');
            $table->dropColumn('et_time_of_et');
            $table->dropColumn('et_endometrium_t');
            $table->dropColumn('et_cathetar');
            $table->dropColumn('et_transfer_stage');
            $table->dropColumn('et_embryo_transfer');
            $table->dropColumn('bt_date_of_et');
            $table->dropColumn('bt_time_of_et');
            $table->dropColumn('bt_endometrium_t');
            $table->dropColumn('bt_cathetar');
            $table->dropColumn('bt_transfer_stage');
            $table->dropColumn('bt_embryo_transfer');
            $table->dropColumn('frozen_stage');
            $table->dropColumn('frozen_blastocyst');
            $table->dropColumn('frozen_embryo_datetime');
            $table->dropColumn('frozen_blastocyst_datetime');
            $table->dropColumn('frozen_straws');
            $table->dropColumn('frozen_mark');
            $table->dropColumn('frozen_plastic_colour');
            $table->dropColumn('frozen_ln2');
            $table->dropColumn('thawing_date_of_et');
            $table->dropColumn('thawing_time_of_et');
            $table->dropColumn('thawing_endometrium_t');
            $table->dropColumn('thawing_cathetar');
            $table->dropColumn('thawing_transfer_stage');
            $table->dropColumn('thawing_embryo_transfer');
        });
    }
}
