<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class UpdateInTestsColumnsTwo extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->text('result_tton')->nullable();
            $table->text('result_by')->nullable();
            $table->text('result_remarks')->nullable();
            $table->text('result_oc_start')->nullable();
            $table->text('result_stop')->nullable();
            $table->text('result_lmp')->nullable();
            $table->text('result_stm_start')->nullable();
            $table->text('result_protocol')->nullable();
            $table->date('result_date_1')->nullable();
            $table->text('result_cyc_day_1')->nullable();
            $table->text('result_stm_day_1')->nullable();
            $table->text('result_end_1')->nullable();
            $table->text('result_rafc_1')->nullable();
            $table->text('result_lafc_1')->nullable();
            $table->text('result_stimulation_1')->nullable();
            $table->text('result_misc_1')->nullable();
            $table->date('result_date_2')->nullable();
            $table->text('result_cyc_day_2')->nullable();
            $table->text('result_stm_day_2')->nullable();
            $table->text('result_end_2')->nullable();
            $table->text('result_rafc_2')->nullable();
            $table->text('result_lafc_2')->nullable();
            $table->text('result_stimulation_2')->nullable();
            $table->text('result_misc_2')->nullable();
            $table->date('result_date_3')->nullable();
            $table->text('result_cyc_day_3')->nullable();
            $table->text('result_stm_day_3')->nullable();
            $table->text('result_end_3')->nullable();
            $table->text('result_rafc_3')->nullable();
            $table->text('result_lafc_3')->nullable();
            $table->text('result_stimulation_3')->nullable();
            $table->text('result_misc_3')->nullable();
            $table->date('result_date_4')->nullable();
            $table->text('result_cyc_day_4')->nullable();
            $table->text('result_stm_day_4')->nullable();
            $table->text('result_end_4')->nullable();
            $table->text('result_rafc_4')->nullable();
            $table->text('result_lafc_4')->nullable();
            $table->text('result_stimulation_4')->nullable();
            $table->text('result_misc_4')->nullable();
            $table->date('result_date_5')->nullable();
            $table->text('result_cyc_day_5')->nullable();
            $table->text('result_stm_day_5')->nullable();
            $table->text('result_end_5')->nullable();
            $table->text('result_rafc_5')->nullable();
            $table->text('result_lafc_5')->nullable();
            $table->text('result_stimulation_5')->nullable();
            $table->text('result_misc_5')->nullable();
            $table->date('result_date_6')->nullable();
            $table->text('result_cyc_day_6')->nullable();
            $table->text('result_stm_day_6')->nullable();
            $table->text('result_end_6')->nullable();
            $table->text('result_rafc_6')->nullable();
            $table->text('result_lafc_6')->nullable();
            $table->text('result_stimulation_6')->nullable();
            $table->text('result_misc_6')->nullable();
            $table->date('result_date_7')->nullable();
            $table->text('result_cyc_day_7')->nullable();
            $table->text('result_stm_day_7')->nullable();
            $table->text('result_end_7')->nullable();
            $table->text('result_rafc_7')->nullable();
            $table->text('result_lafc_7')->nullable();
            $table->text('result_stimulation_7')->nullable();
            $table->text('result_misc_7')->nullable();
            $table->date('result_date_8')->nullable();
            $table->text('result_cyc_day_8')->nullable();
            $table->text('result_stm_day_8')->nullable();
            $table->text('result_end_8')->nullable();
            $table->text('result_rafc_8')->nullable();
            $table->text('result_lafc_8')->nullable();
            $table->text('result_stimulation_8')->nullable();
            $table->text('result_misc_8')->nullable();
            $table->date('result_date_9')->nullable();
            $table->text('result_cyc_day_9')->nullable();
            $table->text('result_stm_day_9')->nullable();
            $table->text('result_end_9')->nullable();
            $table->text('result_rafc_9')->nullable();
            $table->text('result_lafc_9')->nullable();
            $table->text('result_stimulation_9')->nullable();
            $table->text('result_misc_9')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('in_tests', function (Blueprint $table) {
            $table->dropColumn('result_tton');
            $table->dropColumn('result_by');
            $table->dropColumn('result_remarks');
            $table->dropColumn('result_oc_start');
            $table->dropColumn('result_stop');
            $table->dropColumn('result_lmp');
            $table->dropColumn('result_stm_start');
            $table->dropColumn('result_protocol');
            $table->dropColumn('result_date_1');
            $table->dropColumn('result_cyc_day_1');
            $table->dropColumn('result_stm_day_1');
            $table->dropColumn('result_end_1');
            $table->dropColumn('result_rafc_1');
            $table->dropColumn('result_lafc_1');
            $table->dropColumn('result_stimulation_1');
            $table->dropColumn('result_misc_1');
            $table->dropColumn('result_date_2');
            $table->dropColumn('result_cyc_day_2');
            $table->dropColumn('result_stm_day_2');
            $table->dropColumn('result_end_2');
            $table->dropColumn('result_rafc_2');
            $table->dropColumn('result_lafc_2');
            $table->dropColumn('result_stimulation_2');
            $table->dropColumn('result_misc_2');
            $table->dropColumn('result_date_3');
            $table->dropColumn('result_cyc_day_3');
            $table->dropColumn('result_stm_day_3');
            $table->dropColumn('result_end_3');
            $table->dropColumn('result_rafc_3');
            $table->dropColumn('result_lafc_3');
            $table->dropColumn('result_stimulation_3');
            $table->dropColumn('result_misc_3');
            $table->dropColumn('result_date_4');
            $table->dropColumn('result_cyc_day_4');
            $table->dropColumn('result_stm_day_4');
            $table->dropColumn('result_end_4');
            $table->dropColumn('result_rafc_4');
            $table->dropColumn('result_lafc_4');
            $table->dropColumn('result_stimulation_4');
            $table->dropColumn('result_misc_4');
            $table->dropColumn('result_date_5');
            $table->dropColumn('result_cyc_day_5');
            $table->dropColumn('result_stm_day_5');
            $table->dropColumn('result_end_5');
            $table->dropColumn('result_rafc_5');
            $table->dropColumn('result_lafc_5');
            $table->dropColumn('result_stimulation_5');
            $table->dropColumn('result_misc_5');
            $table->dropColumn('result_date_6');
            $table->dropColumn('result_cyc_day_6');
            $table->dropColumn('result_stm_day_6');
            $table->dropColumn('result_end_6');
            $table->dropColumn('result_rafc_6');
            $table->dropColumn('result_lafc_6');
            $table->dropColumn('result_stimulation_6');
            $table->dropColumn('result_misc_6');
            $table->dropColumn('result_date_7');
            $table->dropColumn('result_cyc_day_7');
            $table->dropColumn('result_stm_day_7');
            $table->dropColumn('result_end_7');
            $table->dropColumn('result_rafc_7');
            $table->dropColumn('result_lafc_7');
            $table->dropColumn('result_stimulation_7');
            $table->dropColumn('result_misc_7');
            $table->dropColumn('result_date_8');
            $table->dropColumn('result_cyc_day_8');
            $table->dropColumn('result_stm_day_8');
            $table->dropColumn('result_end_8');
            $table->dropColumn('result_rafc_8');
            $table->dropColumn('result_lafc_8');
            $table->dropColumn('result_stimulation_8');
            $table->dropColumn('result_misc_8');
            $table->dropColumn('result_date_9');
            $table->dropColumn('result_cyc_day_9');
            $table->dropColumn('result_stm_day_9');
            $table->dropColumn('result_end_9');
            $table->dropColumn('result_rafc_9');
            $table->dropColumn('result_lafc_9');
            $table->dropColumn('result_stimulation_9');
            $table->dropColumn('result_misc_9');
        });
    }
}
