<?php

/**
 * InTest
 * @author Ashish Bairagi <https://github.com/abbackend>
 */

namespace App\Models;

use App\Traits\Changable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InTest extends Model
{
    use HasFactory, Changable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'patient_id',
        'p_married_year',
        'p_ttc',
        'p_ttc_year',
        'p_toi',
        'pc_method',
        'pc_duration_year',
        'mh_menarchat',
        'mh_year',
        'mh_previous_cycle',
        'mh_present_cycle',
        'mh_lmp',
        'oh_delivery',
        'oh_miscarriage',
        'oh_pgti',
        'oh_pa',
        'pmh_thyroid',
        'pmh_tuberculosis',
        'pmh_hypertension',
        'pmh_diabetes',
        'pmh_other',
        'sfh_wife',
        'sfh_husband',
        'eve_stature',
        'eve_pulse',
        'eve_height',
        'eve_weight',
        'eve_bp',
        'eve_bmi',
        'eve_anaemia',
        'eve_hyriod',
        'eve_hirsutism',
        'eve_face',
        'eve_breast',
        'eve_other',
        'eve_cvs',
        'eve_rs',
        'eve_sec_sex_character',
        'eve_breast2',
        'eve_public_hair',
        'eve_axillary_hairs',
        'ea_stature',
        'ep_ps',
        'ep_vulva',
        'ep_pv',
        'ep_veg',
        'tr_year',
        'husband_dob',
        'husband_occupation',
        'husband_married_previously',
        'husband_age',
        'husband_children',
        'husband_coitus_frequency',
        'husband_exection',
        'husband_ejaculation',
        'husband_orgasm',
        'husband_drugs',
        'husband_smoking',
        'husband_alcohol',
        'husband_pmh_mumps',
        'husband_pmh_kochs',
        'husband_pmh_diabetes',
        'husband_pmh_hypertension',
        'husband_pmh_previous_sergery',
        'husband_pmh_examination',
        'husband_pmh_stature',
        'husband_pmh_bp',
        'husband_pmh_sec_sex',
        'husband_pmh_genital_examination',
        'husband_semon_analysic',
        'husband_testicular_biospy',
        'husband_other_investigationq',
        'husband_te_advised',
        'husband_i_cbc',
        'husband_i_hb',
        'husband_i_td',
        'husband_i_esr',
        'husband_i_abo',
        'husband_i_hiv',
        'husband_i_blood_sugar',
        'husband_i_hbsag',
        'husband_i_urine',
        'husband_i_hcv',
        'husband_i_semen_culture',
        'husband_i_vdrl',
        'husband_i_sperm',
        'inv_hysteroscopy',
        'inv_laparoscopy',
        'inv_pcr_for_tb',
        'inv_hysterosalpingography',
        'wife_i_cbc',
        'wife_i_hb',
        'wife_i_td',
        'wife_i_esr',
        'wife_i_abo',
        'wife_i_hiv',
        'wife_i_blood_sugar',
        'wife_i_hbsag',
        'wife_i_urine',
        'wife_i_hcv',
        'wife_i_vdrl',
        'he_anh_date',
        'he_anh_day_of_cycle',
        'he_anh_result',
        'he_anh_normal_range',
        'he_prolaction_date',
        'he_prolaction_day_of_cycle',
        'he_prolaction_result',
        'he_prolaction_normal_range',
        'he_lh_date',
        'he_lh_day_of_cycle',
        'he_lh_result',
        'he_lh_normal_range',
        'he_fsh_date',
        'he_fsh_day_of_cycle',
        'he_fsh_result',
        'he_fsh_normal_range',
        'he_testosterone_date',
        'he_testosterone_day_of_cycle',
        'he_testosterone_result',
        'he_testosterone_normal_range',
        'he_oestrogen_date',
        'he_oestrogen_day_of_cycle',
        'he_oestrogen_result',
        'he_oestrogen_normal_range',
        'he_progesterone_date',
        'he_progesterone_day_of_cycle',
        'he_progesterone_result',
        'he_progesterone_normal_range',
        'he_dheas_date',
        'he_dheas_day_of_cycle',
        'he_dheas_result',
        'he_dheas_normal_range',
        'he_cortisol_date',
        'he_cortisol_day_of_cycle',
        'he_cortisol_result',
        'he_cortisol_normal_range',
        'he_t3_date',
        'he_t3_day_of_cycle',
        'he_t3_result',
        'he_t3_normal_range',
        'he_t4_date',
        'he_t4_day_of_cycle',
        'he_t4_result',
        'he_t4_normal_range',
        'he_tsh_date',
        'he_tsh_day_of_cycle',
        'he_tsh_result',
        'he_tsh_normal_range',
        'wife_hea_date',
        'wife_hea_toxoplasma_g',
        'wife_hea_toxoplasma_m',
        'wife_hea_rubella_g',
        'wife_hea_rubella_m',
        'wife_hea_cmv_g',
        'wife_hea_cmv_m',
        'wife_hea_herpes_g',
        'wife_hea_herpes_m',
        'wife_hea_aca_g',
        'wife_hea_aca_m',
        'wife_hea_apa_g',
        'wife_hea_apa_m',
        'wife_hea_ana_g',
        'wife_hea_ana_m',
        'wife_hea_la_g',
        'wife_hea_la_m',
        'sa_hrs_1',
        'wife_ici_day_1',
        'wife_ici_date_1',
        'wife_ici_endo_1',
        'wife_ici_rtov_1',
        'wife_ici_ltov_1',
        'wife_ici_remark_1',
        'wife_ici_day_2',
        'wife_ici_date_2',
        'wife_ici_endo_2',
        'wife_ici_rtov_2',
        'wife_ici_ltov_2',
        'wife_ici_remark_2',
        'wife_ici_day_3',
        'wife_ici_date_3',
        'wife_ici_endo_3',
        'wife_ici_rtov_3',
        'wife_ici_ltov_3',
        'wife_ici_remark_3',
        'wife_ici_day_4',
        'wife_ici_date_4',
        'wife_ici_endo_4',
        'wife_ici_rtov_4',
        'wife_ici_ltov_4',
        'wife_ici_remark_4',
        'wife_ici_day_5',
        'wife_ici_date_5',
        'wife_ici_endo_5',
        'wife_ici_rtov_5',
        'wife_ici_ltov_5',
        'wife_ici_remark_5',
        'wife_ici_day_6',
        'wife_ici_date_6',
        'wife_ici_endo_6',
        'wife_ici_rtov_6',
        'wife_ici_ltov_6',
        'wife_ici_remark_6',
        'wife_iuid_day_1',
        'wife_iuid_volume_1',
        'wife_iuid_native_couint_1',
        'wife_iuid_motility1_1',
        'wife_iuid_harvest_count_1',
        'wife_iuid_motility2_1',
        'wife_iuid_motility3_1',
        'wife_iuid_remark_1',
        'wife_iuid_day_2',
        'wife_iuid_volume_2',
        'wife_iuid_native_couint_2',
        'wife_iuid_motility1_2',
        'wife_iuid_harvest_count_2',
        'wife_iuid_motility2_2',
        'wife_iuid_motility3_2',
        'wife_iuid_remark_2',
        'wife_iuid_day_3',
        'wife_iuid_volume_3',
        'wife_iuid_native_couint_3',
        'wife_iuid_motility1_3',
        'wife_iuid_harvest_count_3',
        'wife_iuid_motility2_3',
        'wife_iuid_motility3_3',
        'wife_iuid_remark_3',
        'wife_iuid_day_4',
        'wife_iuid_volume_4',
        'wife_iuid_native_couint_4',
        'wife_iuid_motility1_4',
        'wife_iuid_harvest_count_4',
        'wife_iuid_motility2_4',
        'wife_iuid_motility3_4',
        'wife_iuid_remark_4',
        'wife_iuid_day_5',
        'wife_iuid_volume_5',
        'wife_iuid_native_couint_5',
        'wife_iuid_motility1_5',
        'wife_iuid_harvest_count_5',
        'wife_iuid_motility2_5',
        'wife_iuid_motility3_5',
        'wife_iuid_remark_5',
        'wife_iuid_day_6',
        'wife_iuid_volume_6',
        'wife_iuid_native_couint_6',
        'wife_iuid_motility1_6',
        'wife_iuid_harvest_count_6',
        'wife_iuid_motility2_6',
        'wife_iuid_motility3_6',
        'wife_iuid_remark_6',
        'result_description',
        'result_tton',
        'result_remarks',
        'result_by',
        'wife_lmp_oc_begin',
        'wife_lmp_oc_stopped',
        'wife_lmp_oc_tco',
        'wife_lmp_telephone_begin',
        'wife_lmp_telephone_stopped',
        'wife_lmp_telephone_tco',
        'wife_lmp_discussion_begin',
        'wife_lmp_discussion_stopped',
        'wife_lmp_discussion_tco',
        'wife_lmp_lupride',
        'wife_lmp_stared',
        'wife_lmp_tocome',
        'wife_lmp_protocol',
        'result_lmp',
        'result_stm_start',
        'result_date_1',
        'result_cyc_day_1',
        'result_stm_day_1',
        'result_end_1',
        'result_rafc_1',
        'result_lafc_1',
        'result_stimulation_1',
        'result_misc_1',
        'result_date_2',
        'result_cyc_day_2',
        'result_stm_day_2',
        'result_end_2',
        'result_rafc_2',
        'result_lafc_2',
        'result_stimulation_2',
        'result_misc_2',
        'result_date_3',
        'result_cyc_day_3',
        'result_stm_day_3',
        'result_end_3',
        'result_rafc_3',
        'result_lafc_3',
        'result_stimulation_3',
        'result_misc_3',
        'result_date_4',
        'result_cyc_day_4',
        'result_stm_day_4',
        'result_end_4',
        'result_rafc_4',
        'result_lafc_4',
        'result_stimulation_4',
        'result_misc_4',
        'result_date_5',
        'result_cyc_day_5',
        'result_stm_day_5',
        'result_end_5',
        'result_rafc_5',
        'result_lafc_5',
        'result_stimulation_5',
        'result_misc_5',
        'result_date_6',
        'result_cyc_day_6',
        'result_stm_day_6',
        'result_end_6',
        'result_rafc_6',
        'result_lafc_6',
        'result_stimulation_6',
        'result_misc_6',
        'result_date_7',
        'result_cyc_day_7',
        'result_stm_day_7',
        'result_end_7',
        'result_rafc_7',
        'result_lafc_7',
        'result_stimulation_7',
        'result_misc_7',
        'result_date_8',
        'result_cyc_day_8',
        'result_stm_day_8',
        'result_end_8',
        'result_rafc_8',
        'result_lafc_8',
        'result_stimulation_8',
        'result_misc_8',
        'result_date_9',
        'result_cyc_day_9',
        'result_stm_day_9',
        'result_end_9',
        'result_rafc_9',
        'result_lafc_9',
        'result_stimulation_9',
        'result_misc_9',
        'result_date_10',
        'result_cyc_day_10',
        'result_stm_day_10',
        'result_end_10',
        'result_rafc_10',
        'result_lafc_10',
        'result_stimulation_10',
        'result_misc_10',
        'result_date_11',
        'result_cyc_day_11',
        'result_stm_day_11',
        'result_end_11',
        'result_rafc_11',
        'result_lafc_11',
        'result_stimulation_11',
        'result_misc_11',
        'result_date_12',
        'result_cyc_day_12',
        'result_stm_day_12',
        'result_end_12',
        'result_rafc_12',
        'result_lafc_12',
        'result_stimulation_12',
        'result_misc_12',
        'result_date_13',
        'result_cyc_day_13',
        'result_stm_day_13',
        'result_end_13',
        'result_rafc_13',
        'result_lafc_13',
        'result_stimulation_13',
        'result_misc_13',
        'result_date_14',
        'result_cyc_day_14',
        'result_stm_day_14',
        'result_end_14',
        'result_rafc_14',
        'result_lafc_14',
        'result_stimulation_14',
        'result_misc_14',
        'result_date_15',
        'result_cyc_day_15',
        'result_stm_day_15',
        'result_end_15',
        'result_rafc_15',
        'result_lafc_15',
        'result_stimulation_15',
        'result_misc_15',
        'result_date_16',
        'result_cyc_day_16',
        'result_stm_day_16',
        'result_end_16',
        'result_rafc_16',
        'result_lafc_16',
        'result_stimulation_16',
        'result_misc_16',
        'wife_lmp_lh',
        'wife_lmp_e2',
        'wife_lmp_inj',
        'wife_lmp_dose',
        'wife_lmp_hcg',
        'wife_lmp_hcg_day',
        'wife_lmp_opu',
        'wife_lmp_ampm',
        'sperm_source_folliciles_right',
        'sperm_source_folliciles_left',
        'sperm_source_folliciles_total',
        'sperm_source_ovum_right',
        'sperm_source_ovum_left',
        'sperm_source_ovum_pod',
        'sperm_source_ovum_total',
        'oocyte_quality_1_no',
        'oocyte_quality_1_stage',
        'oocyte_quality_2_no',
        'oocyte_quality_2_stage',
        'oocyte_quality_3_no',
        'oocyte_quality_3_stage',
        'oocyte_quality_4_no',
        'oocyte_quality_4_stage',
        'oocyte_quality_5_no',
        'oocyte_quality_5_stage',
        'sperm_source_ejaculated',
        'sperm_source_donor',
        'sperm_source_pesa',
        'sperm_source_cryo',
        'sperm_source_test',
        'sperm_source_recovery',
        'sperm_source_whom',
        'sperm_source_when',
        'sa_volume_native',
        'sa_volume_ah',
        'sa_mucoid_native',
        'sa_mucoid_ah',
        'sa_sperm_count_native',
        'sa_sperm_count_ah',
        'sa_motility_native',
        'sa_motility_ah',
        'sa_grade_native',
        'sa_grade_ah',
        'sa_pus_cells_native',
        'sa_pus_cells_ah',
        'sa_immature_cells_native',
        'sa_immature_cells_ah',
        'sa_agglutination_native',
        'sa_agglutination_ah',
        'sa_granular_debris_native',
        'sa_granular_debris_ah',
        'sa_insemination_time_native',
        'sa_insemination_time_ah',
        'result_ivf',
        'result_icsi',
        'sa_no2pn_1',
        'sa_2pn_1',
        'sa_max2pn_1',
        'sa_no2pn_2',
        'sa_2pn_2',
        'sa_max2pn_2',
        'et_date_of_et',
        'et_time_of_et',
        'et_endometrium_t',
        'et_cathetar',
        'et_transfer_stage',
        'et_embryo_transfer',
        'bt_date_of_et',
        'bt_time_of_et',
        'bt_endometrium_t',
        'bt_cathetar',
        'bt_transfer_stage',
        'bt_embryo_transfer',
        'frozen_stage',
        'frozen_blastocyst',
        'frozen_embryo_datetime',
        'frozen_blastocyst_datetime',
        'frozen_straws',
        'frozen_mark',
        'frozen_plastic_colour',
        'frozen_ln2',
        'thawing_date_of_et',
        'thawing_time_of_et',
        'thawing_endometrium_t',
        'thawing_cathetar',
        'thawing_transfer_stage',
        'thawing_embryo_transfer',
        'result_eudate',
        'result_bhcg',
        'result_semen_cryo'
    ];

    protected $casts = ['inv_images' => 'array'];

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function history()
    {
        return $this->hasMany(TestHistory::class, 'test_id', 'id');
    }

    public function setInvImages(array $images): self
    {
        $this->inv_images = array_values(array_unique($images));

        return $this;
    }

    public function getFileByIndex(int $index): string
    {
        return $this->inv_images[$index];
    }

    /*******************************************
    * Query Scopes
    *******************************************/
    public function scopeForPatient($query, $patient)
    {
        return $query->where('patient_id', ($patient instanceof Patient) ? $patient->id : $patient);
    }

    /**
     * Maintain the history.
     */
    private function getChangableProperty(): array
    {
        return [
            'Married Year' => $this->p_married_year,
            'Trying to conceive' => $this->p_ttc,
            'Year' => $this->p_ttc_year,
            'Type of infertility' => $this->p_toi,
            'Previous Contraception > Method' => $this->pc_method,
            'Previous Contraception > Duration year' => $this->pc_duration_year,
            'Method History > Menarch at' => $this->mh_menarchat,
            'Method History > Year' => $this->mh_year,
            'Method History > Previous cycle' => $this->mh_previous_cycle,
            'Method History > Present cycle' => $this->mh_present_cycle,
            'Method History > L.M.P' => $this->mh_lmp,
            'Obsteric History > Delivery' => $this->oh_delivery,
            'Obsteric History > Miscarriage' => $this->oh_miscarriage,
            'Obsteric History > Previous genital tract infection' => $this->oh_pgti,
            'Obsteric History > Previous abdominal / Gynaecological surgery' => $this->oh_pa,
            'Previous Medical History > Thyroid' => $this->pmh_thyroid,
            'Previous Medical History > Tuberculosis' => $this->pmh_tuberculosis,
            'Previous Medical History > Hypertension' => $this->pmh_hypertension,
            'Previous Medical History > Diabetes' => $this->pmh_diabetes,
            'Previous Medical History > Other' => $this->pmh_other,
            'Significant Family History > Wife' => $this->sfh_wife,
            'Significant Family History > Husband' => $this->sfh_husband,
            'Examination > Stature' => $this->eve_stature,
            'Examination > Pulse' => $this->eve_pulse,
            'Examination > Height' => $this->eve_height,
            'Examination > Weight' => $this->eve_weight,
            'Examination > B.P' => $this->eve_bp,
            'Examination > BMI' => $this->eve_bmi,
            'Examination > Anaemia' => $this->eve_anaemia,
            'Examination > Thyriod' => $this->eve_hyriod,
            'Examination > Hirsutism' => $this->eve_hirsutism,
            'Examination > Face' => $this->eve_face,
            'Examination > Breast' => $this->eve_breast,
            'Examination > Other' => $this->eve_other,
            'Examination > C.V.S' => $this->eve_cvs,
            'Examination > R.S' => $this->eve_rs,
            'Examination > Sec. Sex Character' => $this->eve_sec_sex_character,
            'Examination > Breast' => $this->eve_breast2,
            'Examination > Public hair' => $this->eve_public_hair,
            'Examination > Axillary hairs' => $this->eve_axillary_hairs,
            'Abdomainal Examination > Stature' => $this->ea_stature,
            'Pelvic Examination > PS' => $this->ep_ps,
            'Pelvic Examination > Vulva' => $this->ep_vulva,
            'Pelvic Examination > PV' => $this->ep_pv,
            'Pelvic Examination > Vagina' => $this->ep_veg,
            'Teatment Received > Year' => $this->tr_year,
            'Husband > Date of birth' => $this->husband_dob,
            'Husband > Occupation' => $this->husband_occupation,
            'Husband > Married Previously' => $this->husband_married_previously,
            'Husband > Age' => $this->husband_age,
            'Husband > Children' => $this->husband_children,
            'Husband > Coitus frequency' => $this->husband_coitus_frequency,
            'Husband > Exection' => $this->husband_exection,
            'Husband > Ejaculation' => $this->husband_ejaculation,
            'Husband > Orgasm' => $this->husband_orgasm,
            'Husband > Drugs' => $this->husband_drugs,
            'Husband > Smoking' => $this->husband_smoking,
            'Husband > Alcohol' => $this->husband_alcohol,
            'Previous Medical History > Semon Analysic' => $this->husband_semon_analysic,
            'Wife > Hysteroscopy' => $this->inv_hysteroscopy,
            'Wife > Laparoscopy' => $this->inv_laparoscopy,
            'Wife > PCR for TB' => $this->inv_pcr_for_tb,
            'Wife > Hysterosalpingography' => $this->inv_hysterosalpingography,
            'Hormonal Estimation > Serum (ANH) > Date' => $this->he_anh_date,
            'Hormonal Estimation > Serum (ANH) > Day of cycle' => $this->he_anh_day_of_cycle,
            'Hormonal Estimation > Serum (ANH) > Result' => $this->he_anh_result,
            'Hormonal Estimation > Serum (ANH) > Normal range' => $this->he_anh_normal_range,
            'Hormonal Estimation > Serum (Prolaction) > Date' => $this->he_prolaction_date,
            'Hormonal Estimation > Serum (Prolaction) > Day of cycle' => $this->he_prolaction_day_of_cycle,
            'Hormonal Estimation > Serum (Prolaction) > Result' => $this->he_prolaction_result,
            'Hormonal Estimation > Serum (Prolaction) > Normal range' => $this->he_prolaction_normal_range,
            'Hormonal Estimation > Serum (L.H) > Date' => $this->he_lh_date,
            'Hormonal Estimation > Serum (L.H) > Day of cycle' => $this->he_lh_day_of_cycle,
            'Hormonal Estimation > Serum (L.H) > Result' => $this->he_lh_result,
            'Hormonal Estimation > Serum (L.H) > Normal range' => $this->he_lh_normal_range,
            'Hormonal Estimation > Serum (F.S.H) > Date' => $this->he_fsh_date,
            'Hormonal Estimation > Serum (F.S.H) > Day of cycle' => $this->he_fsh_day_of_cycle,
            'Hormonal Estimation > Serum (F.S.H) > Result' => $this->he_fsh_result,
            'Hormonal Estimation > Serum (F.S.H) > Normal range' => $this->he_fsh_normal_range,
            'Hormonal Estimation > Serum (Testosterone) > Date' => $this->he_testosterone_date,
            'Hormonal Estimation > Serum (Testosterone) > Day of cycle' => $this->he_testosterone_day_of_cycle,
            'Hormonal Estimation > Serum (Testosterone) > Result' => $this->he_testosterone_result,
            'Hormonal Estimation > Serum (Testosterone) > Normal range' => $this->he_testosterone_normal_range,
            'Hormonal Estimation > Serum (Oestrogen) > Date' => $this->he_oestrogen_date,
            'Hormonal Estimation > Serum (Oestrogen) > Day of cycle' => $this->he_oestrogen_day_of_cycle,
            'Hormonal Estimation > Serum (Oestrogen) > Result' => $this->he_oestrogen_result,
            'Hormonal Estimation > Serum (Oestrogen) > Normal range' => $this->he_oestrogen_normal_range,
            'Hormonal Estimation > Serum (Progesterone) > Date' => $this->he_progesterone_date,
            'Hormonal Estimation > Serum (Progesterone) > Day of cycle' => $this->he_progesterone_day_of_cycle,
            'Hormonal Estimation > Serum (Progesterone) > Result' => $this->he_progesterone_result,
            'Hormonal Estimation > Serum (Progesterone) > Normal range' => $this->he_progesterone_normal_range,
            'Hormonal Estimation > Serum (DHEAS) > Date' => $this->he_dheas_date,
            'Hormonal Estimation > Serum (DHEAS) > Day of cycle' => $this->he_dheas_day_of_cycle,
            'Hormonal Estimation > Serum (DHEAS) > Result' => $this->he_dheas_result,
            'Hormonal Estimation > Serum (DHEAS) > Normal range' => $this->he_dheas_normal_range,
            'Hormonal Estimation > Serum (Cortisol) > Date' => $this->he_cortisol_date,
            'Hormonal Estimation > Serum (Cortisol) > Day of cycle' => $this->he_cortisol_day_of_cycle,
            'Hormonal Estimation > Serum (Cortisol) > Result' => $this->he_cortisol_result,
            'Hormonal Estimation > Serum (Cortisol) > Normal range' => $this->he_cortisol_normal_range,
            'Hormonal Estimation > Serum (T3) > Date' => $this->he_t3_date,
            'Hormonal Estimation > Serum (T3) > Day of cycle' => $this->he_t3_day_of_cycle,
            'Hormonal Estimation > Serum (T3) > Result' => $this->he_t3_result,
            'Hormonal Estimation > Serum (T3) > Normal range' => $this->he_t3_normal_range,
            'Hormonal Estimation > Serum (T4) > Date' => $this->he_t4_date,
            'Hormonal Estimation > Serum (T4) > Day of cycle' => $this->he_t4_day_of_cycle,
            'Hormonal Estimation > Serum (T4) > Result' => $this->he_t4_result,
            'Hormonal Estimation > Serum (T4) > Normal range' => $this->he_t4_normal_range,
            'Hormonal Estimation > Serum (TSH) > Date' => $this->he_tsh_date,
            'Hormonal Estimation > Serum (TSH) > Day of cycle' => $this->he_tsh_day_of_cycle,
            'Hormonal Estimation > Serum (TSH) > Result' => $this->he_tsh_result,
            'Hormonal Estimation > Serum (TSH) > Normal range' => $this->he_tsh_normal_range,
            'OI > Plan' => $this->oi_plan,
            'OI > IUI' => $this->oi_iui,
            'OI > IUF' => $this->oi_iuf,
            'Previous Medical History > Mumps' => $this->husband_pmh_mumps,
            "Previous Medical History > Koch's" => $this->husband_pmh_kochs,
            'Previous Medical History > Diabetes' => $this->husband_pmh_diabetes,
            'Previous Medical History > Hypertension' => $this->husband_pmh_hypertension,
            'Previous Medical History > Previous Sergery' => $this->husband_pmh_previous_sergery,
            'Previous Medical History > Examination' => $this->husband_pmh_examination,
            'Previous Medical History > Stature' => $this->husband_pmh_stature,
            'Previous Medical History > B.P' => $this->husband_pmh_bp,
            'Previous Medical History > Sec. Sex Character' => $this->husband_pmh_sec_sex,
            'Previous Medical History > Genital Examination' => $this->husband_pmh_genital_examination,
            'Previous Medical History > Testicular Biospy' => $this->husband_testicular_biospy,
            'Previous Medical History > Other Investigationq' => $this->husband_other_investigationq,
            'Previous Medical History > T/E Advised' => $this->husband_te_advised,
            'Husband > Investigations > CBC' => $this->husband_i_cbc,
            'Husband > Investigations > HB' => $this->husband_i_hb,
            'Husband > Investigations > T & D' => $this->husband_i_td,
            'Husband > Investigations > ESR' => $this->husband_i_esr,
            'Husband > Investigations > ABO-RH' => $this->husband_i_abo,
            'Husband > Investigations > HIV I & II' => $this->husband_i_hiv,
            'Husband > Investigations > Blood Sugar' => $this->husband_i_blood_sugar,
            'Husband > Investigations > HbsAg' => $this->husband_i_hbsag,
            'Husband > Investigations > Urine' => $this->husband_i_urine,
            'Husband > Investigations > HCV' => $this->husband_i_hcv,
            'Husband > Investigations > Semen Culture' => $this->husband_i_semen_culture,
            'Husband > Investigations > VDRL' => $this->husband_i_vdrl,
            'Husband > Investigations > Sperm Antibodies' => $this->husband_i_sperm,
            'Wife > Investigations > CBC' => $this->wife_i_cbc,
            'Wife > Investigations > HB' => $this->wife_i_hb,
            'Wife > Investigations > T & D' => $this->wife_i_td,
            'Wife > Investigations > ESR' => $this->wife_i_esr,
            'Wife > Investigations > ABO-RH' => $this->wife_i_abo,
            'Wife > Investigations > HIV I & II' => $this->wife_i_hiv,
            'Wife > Investigations > Blood Sugar' => $this->wife_i_blood_sugar,
            'Wife > Investigations > HbsAg' => $this->wife_i_hbsag,
            'Wife > Investigations > Urine' => $this->wife_i_urine,
            'Wife > Investigations > HCV' => $this->wife_i_hcv,
            'Wife > Investigations > VDRL' => $this->wife_i_vdrl,
            "Hormonal Estimation > Antibodies against husband's sperms > Date" => $this->wife_hea_date,
            "Hormonal Estimation > Antibodies against husband's sperms > Toxoplasma > lgG" => $this->wife_hea_toxoplasma_g,
            "Hormonal Estimation > Antibodies against husband's sperms > Toxoplasma > lgM" => $this->wife_hea_toxoplasma_m,
            "Hormonal Estimation > Antibodies against husband's sperms > Rubella > lgG" => $this->wife_hea_rubella_g,
            "Hormonal Estimation > Antibodies against husband's sperms > Rubella > lgM" => $this->wife_hea_rubella_m,
            "Hormonal Estimation > Antibodies against husband's sperms > C.M.V > lgG" => $this->wife_hea_cmv_g,
            "Hormonal Estimation > Antibodies against husband's sperms > C.M.V > lgM" => $this->wife_hea_cmv_m,
            "Hormonal Estimation > Antibodies against husband's sperms > Herpes > lgG" => $this->wife_hea_herpes_g,
            "Hormonal Estimation > Antibodies against husband's sperms > Herpes > lgM" => $this->wife_hea_herpes_m,
            "Hormonal Estimation > Antibodies against husband's sperms > ACA > lgG" => $this->wife_hea_aca_g,
            "Hormonal Estimation > Antibodies against husband's sperms > ACA > lgM" => $this->wife_hea_aca_m,
            "Hormonal Estimation > Antibodies against husband's sperms > APA > lgG" => $this->wife_hea_apa_g,
            "Hormonal Estimation > Antibodies against husband's sperms > APA > lgM" => $this->wife_hea_apa_m,
            "Hormonal Estimation > Antibodies against husband's sperms > ANA > lgG" => $this->wife_hea_ana_g,
            "Hormonal Estimation > Antibodies against husband's sperms > ANA > lgM" => $this->wife_hea_ana_m,
            "Hormonal Estimation > Antibodies against husband's sperms > LA > lgG" => $this->wife_hea_la_g,
            "Hormonal Estimation > Antibodies against husband's sperms > LA > lgM" => $this->wife_hea_la_m,
            'Chromosomal Analysis > ICI Cycle > # (1) > Day' => $this->wife_ici_day_1,
            'Chromosomal Analysis > ICI Cycle > # (1) > Date' => $this->wife_ici_date_1,
            'Chromosomal Analysis > ICI Cycle > # (1) > Endo.' => $this->wife_ici_endo_1,
            'Chromosomal Analysis > ICI Cycle > # (1) > Rt. Ov.' => $this->wife_ici_rtov_1,
            'Chromosomal Analysis > ICI Cycle > # (1) > Lt. Ov.' => $this->wife_ici_ltov_1,
            'Chromosomal Analysis > ICI Cycle > # (1) > Remark' => $this->wife_ici_remark_1,
            'Chromosomal Analysis > ICI Cycle > # (2) > Day' => $this->wife_ici_day_2,
            'Chromosomal Analysis > ICI Cycle > # (2) > Date' => $this->wife_ici_date_2,
            'Chromosomal Analysis > ICI Cycle > # (2) > Endo.' => $this->wife_ici_endo_2,
            'Chromosomal Analysis > ICI Cycle > # (2) > Rt. Ov.' => $this->wife_ici_rtov_2,
            'Chromosomal Analysis > ICI Cycle > # (2) > Lt. Ov.' => $this->wife_ici_ltov_2,
            'Chromosomal Analysis > ICI Cycle > # (2) > Remark' => $this->wife_ici_remark_2,
            'Chromosomal Analysis > ICI Cycle > # (3) > Day' => $this->wife_ici_day_3,
            'Chromosomal Analysis > ICI Cycle > # (3) > Date' => $this->wife_ici_date_3,
            'Chromosomal Analysis > ICI Cycle > # (3) > Endo.' => $this->wife_ici_endo_3,
            'Chromosomal Analysis > ICI Cycle > # (3) > Rt. Ov.' => $this->wife_ici_rtov_3,
            'Chromosomal Analysis > ICI Cycle > # (3) > Lt. Ov.' => $this->wife_ici_ltov_3,
            'Chromosomal Analysis > ICI Cycle > # (3) > Remark' => $this->wife_ici_remark_3,
            'Chromosomal Analysis > ICI Cycle > # (4) > Day' => $this->wife_ici_day_4,
            'Chromosomal Analysis > ICI Cycle > # (4) > Date' => $this->wife_ici_date_4,
            'Chromosomal Analysis > ICI Cycle > # (4) > Endo.' => $this->wife_ici_endo_4,
            'Chromosomal Analysis > ICI Cycle > # (4) > Rt. Ov.' => $this->wife_ici_rtov_4,
            'Chromosomal Analysis > ICI Cycle > # (4) > Lt. Ov.' => $this->wife_ici_ltov_4,
            'Chromosomal Analysis > ICI Cycle > # (4) > Remark' => $this->wife_ici_remark_4,
            'Chromosomal Analysis > ICI Cycle > # (5) > Day' => $this->wife_ici_day_5,
            'Chromosomal Analysis > ICI Cycle > # (5) > Date' => $this->wife_ici_date_5,
            'Chromosomal Analysis > ICI Cycle > # (5) > Endo.' => $this->wife_ici_endo_5,
            'Chromosomal Analysis > ICI Cycle > # (5) > Rt. Ov.' => $this->wife_ici_rtov_5,
            'Chromosomal Analysis > ICI Cycle > # (5) > Lt. Ov.' => $this->wife_ici_ltov_5,
            'Chromosomal Analysis > ICI Cycle > # (5) > Remark' => $this->wife_ici_remark_5,
            'Chromosomal Analysis > ICI Cycle > # (6) > Day' => $this->wife_ici_day_6,
            'Chromosomal Analysis > ICI Cycle > # (6) > Date' => $this->wife_ici_date_6,
            'Chromosomal Analysis > ICI Cycle > # (6) > Endo.' => $this->wife_ici_endo_6,
            'Chromosomal Analysis > ICI Cycle > # (6) > Rt. Ov.' => $this->wife_ici_rtov_6,
            'Chromosomal Analysis > ICI Cycle > # (6) > Lt. Ov.' => $this->wife_ici_ltov_6,
            'Chromosomal Analysis > ICI Cycle > # (6) > Remark' => $this->wife_ici_remark_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Day' => $this->wife_iuid_day_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Volume' => $this->wife_iuid_volume_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Native Couint' => $this->wife_iuid_native_couint_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Motility(I)' => $this->wife_iuid_motility1_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Harvest Count' => $this->wife_iuid_harvest_count_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Motility(II)' => $this->wife_iuid_motility2_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Motility(III)' => $this->wife_iuid_motility3_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (1) > Remark' => $this->wife_iuid_remark_1,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Day' => $this->wife_iuid_day_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Volume' => $this->wife_iuid_volume_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Native Couint' => $this->wife_iuid_native_couint_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Motility(I)' => $this->wife_iuid_motility1_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Harvest Count' => $this->wife_iuid_harvest_count_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Motility(II)' => $this->wife_iuid_motility2_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Motility(III)' => $this->wife_iuid_motility3_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (2) > Remark' => $this->wife_iuid_remark_2,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Day' => $this->wife_iuid_day_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Volume' => $this->wife_iuid_volume_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Native Couint' => $this->wife_iuid_native_couint_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Motility(I)' => $this->wife_iuid_motility1_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Harvest Count' => $this->wife_iuid_harvest_count_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Motility(II)' => $this->wife_iuid_motility2_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Motility(III)' => $this->wife_iuid_motility3_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (3) > Remark' => $this->wife_iuid_remark_3,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Day' => $this->wife_iuid_day_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Volume' => $this->wife_iuid_volume_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Native Couint' => $this->wife_iuid_native_couint_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Motility(I)' => $this->wife_iuid_motility1_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Harvest Count' => $this->wife_iuid_harvest_count_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Motility(II)' => $this->wife_iuid_motility2_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Motility(III)' => $this->wife_iuid_motility3_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (4) > Remark' => $this->wife_iuid_remark_4,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Day' => $this->wife_iuid_day_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Volume' => $this->wife_iuid_volume_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Native Couint' => $this->wife_iuid_native_couint_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Motility(I)' => $this->wife_iuid_motility1_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Harvest Count' => $this->wife_iuid_harvest_count_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Motility(II)' => $this->wife_iuid_motility2_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Motility(III)' => $this->wife_iuid_motility3_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (5) > Remark' => $this->wife_iuid_remark_5,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Day' => $this->wife_iuid_day_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Volume' => $this->wife_iuid_volume_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Native Couint' => $this->wife_iuid_native_couint_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Motility(I)' => $this->wife_iuid_motility1_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Harvest Count' => $this->wife_iuid_harvest_count_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Motility(II)' => $this->wife_iuid_motility2_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Motility(III)' => $this->wife_iuid_motility3_6,
            'Chromosomal Analysis > Intra-Uterine Insemination Details > # (6) > Remark' => $this->wife_iuid_remark_6,
            "IVF Treatment Plan > Wife's LMP." => $this->result_description,
            "IVF Treatment Plan > Wife's LMP. > O.C. > Begin on" => $this->wife_lmp_oc_begin,
            "IVF Treatment Plan > Wife's LMP. > O.C. > Stopped on" => $this->wife_lmp_oc_stopped,
            "IVF Treatment Plan > Wife's LMP. > O.C. > TCO" => $this->wife_lmp_oc_tco,
            "IVF Treatment Plan > Wife's LMP. > Telephone Talk > Begin on" => $this->wife_lmp_telephone_begin,
            "IVF Treatment Plan > Wife's LMP. > Telephone Talk > Stopped on" => $this->wife_lmp_telephone_stopped,
            "IVF Treatment Plan > Wife's LMP. > Telephone Talk > TCO" => $this->wife_lmp_telephone_tco,
            "IVF Treatment Plan > Wife's LMP. > Discussion > Begin on" => $this->wife_lmp_discussion_begin,
            "IVF Treatment Plan > Wife's LMP. > Discussion > Stopped on" => $this->wife_lmp_discussion_stopped,
            "IVF Treatment Plan > Wife's LMP. > Discussion > TCO" => $this->wife_lmp_discussion_tco,
            "IVF Treatment Plan > Wife's LMP. > Lupride" => $this->wife_lmp_lupride,
            "IVF Treatment Plan > Wife's LMP. > Stared" => $this->wife_lmp_stared,
            "IVF Treatment Plan > Wife's LMP. > To Come On" => $this->wife_lmp_tocome,
            "IVF Treatment Plan > Wife's LMP. > Protocol" => $this->wife_lmp_protocol,
            "IVF Treatment Plan > Wife's LMP. > Inj." => $this->wife_lmp_inj,
            "IVF Treatment Plan > Wife's LMP. > Dose" => $this->wife_lmp_dose,
            "IVF Treatment Plan > Wife's LMP. > HCG" => $this->wife_lmp_hcg,
            "IVF Treatment Plan > Wife's LMP. > LH" => $this->wife_lmp_lh,
            "IVF Treatment Plan > Wife's LMP. > E2" => $this->wife_lmp_e2,
            "IVF Treatment Plan > Wife's LMP. > Day Of HCG" => $this->wife_lmp_hcg_day,
            "IVF Treatment Plan > Wife's LMP. > OPU" => $this->wife_lmp_opu,
            "IVF Treatment Plan > Wife's LMP. > AM/PM" => $this->wife_lmp_ampm,
            "IVF Treatment Plan > Wife's LMP. > Egg. Recovery" => $this->wife_lmp_egg_recovery,
            "IVF Treatment Plan > Wife's LMP. > Ealry Cleavage" => $this->wife_lmp_cleavage,
            "IVF Treatment Plan > Wife's LMP. > Stage Of Embryos" => $this->wife_lmp_embryos_stage,
            "IVF Treatment Plan > Wife's LMP. > No Of Embroyo's Transferred" => $this->wife_lmp_embryos_transferred,
            "IVF Treatment Plan > Wife's LMP. > E.T." => $this->wife_lmp_et,
            "IVF Treatment Plan > Wife's LMP. > Cryo. Of Embryo" => $this->wife_lmp_cryo,
            "IVF Treatment Plan > Wife's LMP. > Semen Cryo Preservation" => $this->wife_semen_preservation,
            "IVF Treatment Plan > Wife's LMP. > Semen Thowing Report" => $this->wife_semen_report,
            'Sperm Source > Ejaculated' => $this->sperm_source_ejaculated,
            'Sperm Source > Donor' => $this->sperm_source_donor,
            'Sperm Source > Pesa' => $this->sperm_source_pesa,
            'Sperm Source > Cryo (Cord No.)' => $this->sperm_source_cryo,
            'Sperm Source > Test' => $this->sperm_source_test,
            'Sperm Source > Recovery Checked' => $this->sperm_source_recovery,
            'Sperm Source > Whom' => $this->sperm_source_whom,
            'Sperm Source > When' => $this->sperm_source_when,
            'Sperm Source > Infertility Type' => $this->sperm_source_infertility_type,
            'Sperm Source > Age' => $this->sperm_source_age,
            'Sperm Source > L.M.P' => $this->sperm_source_lmp,
            'Sperm Source > Down regulation started on date' => $this->sperm_source_drd,
            'Sperm Source > Endometrium Thickness' => $this->sperm_source_et,
            'Sperm Source > # (1) > Stimulation started on date' => $this->sperm_source_ss_date_1,
            'Sperm Source > # (1) > Date' => $this->sperm_source_date_1,
            'Sperm Source > # (1) > E2' => $this->sperm_source_e2_1,
            'Sperm Source > # (1) > LH' => $this->sperm_source_lh_1,
            'Sperm Source > # (2) > Stimulation started on date' => $this->sperm_source_ss_date_2,
            'Sperm Source > # (2) > Date' => $this->sperm_source_date_2,
            'Sperm Source > # (2) > E2' => $this->sperm_source_e2_2,
            'Sperm Source > # (2) > LH' => $this->sperm_source_lh_2,
            'Sperm Source > # (3) > Stimulation started on date' => $this->sperm_source_ss_date_3,
            'Sperm Source > # (3) > Date' => $this->sperm_source_date_3,
            'Sperm Source > # (3) > E2' => $this->sperm_source_e2_3,
            'Sperm Source > # (3) > LH' => $this->sperm_source_lh_3,
            'Sperm Source > HCG Previously Supply giving' => $this->sperm_source_hcg,
            'Sperm Source > Date of ovum Pick up Day/Time' => $this->sperm_source_ovum,
            'Sperm Source > Type of Media used' => $this->sperm_source_media_type,
            'Sperm Source > Total No. of Follicles (Right)' => $this->sperm_source_folliciles_right,
            'Sperm Source > Total No. of Follicles (Left)' => $this->sperm_source_folliciles_left,
            'Sperm Source > Total No. of Follicles' => $this->sperm_source_folliciles_total,
            'Sperm Source > Total No. of Ovum Retrieve (Right)' => $this->sperm_source_ovum_right,
            'Sperm Source > Total No. of Ovum Retrieve (Left)' => $this->sperm_source_ovum_left,
            'Sperm Source > Total No. of Ovum Retrieve (POD)' => $this->sperm_source_ovum_pod,
            'Sperm Source > Total No. of Ovum Retrieve' => $this->sperm_source_ovum_total,
            'OOCYTE QUALITY > Plate No. (1) > No. of Oocyte' => $this->oocyte_quality_1_no,
            'OOCYTE QUALITY > Plate No. (1) > Maturation Stage' => $this->oocyte_quality_1_stage,
            'OOCYTE QUALITY > Plate No. (2) > No. of Oocyte' => $this->oocyte_quality_2_no,
            'OOCYTE QUALITY > Plate No. (2) > Maturation Stage' => $this->oocyte_quality_2_stage,
            'OOCYTE QUALITY > Plate No. (3) > No. of Oocyte' => $this->oocyte_quality_3_no,
            'OOCYTE QUALITY > Plate No. (3) > Maturation Stage' => $this->oocyte_quality_3_stage,
            'OOCYTE QUALITY > Plate No. (4) > No. of Oocyte' => $this->oocyte_quality_4_no,
            'OOCYTE QUALITY > Plate No. (4) > Maturation Stage' => $this->oocyte_quality_4_stage,
            'OOCYTE QUALITY > Plate No. (5) > No. of Oocyte' => $this->oocyte_quality_5_no,
            'OOCYTE QUALITY > Plate No. (5) > Maturation Stage' => $this->oocyte_quality_5_stage,
            'OOCYTE QUALITY > Plate No. (6) > No. of Oocyte' => $this->oocyte_quality_6_no,
            'OOCYTE QUALITY > Plate No. (6) > Maturation Stage' => $this->oocyte_quality_6_stage,
            'OOCYTE QUALITY > Semen Analysis (Volume) > Native' => $this->sa_volume_native,
            'OOCYTE QUALITY > Semen Analysis (Volume) > After Harvest' => $this->sa_volume_ah,
            'OOCYTE QUALITY > Semen Analysis (Mucoid) > Native' => $this->sa_mucoid_native,
            'OOCYTE QUALITY > Semen Analysis (Mucoid) > After Harvest' => $this->sa_mucoid_ah,
            'OOCYTE QUALITY > Semen Analysis (Sperm Count/ml) > Native' => $this->sa_sperm_count_native,
            'OOCYTE QUALITY > Semen Analysis (Sperm Count/ml) > After Harvest' => $this->sa_sperm_count_ah,
            'OOCYTE QUALITY > Semen Analysis (Motility) > Native' => $this->sa_motility_native,
            'OOCYTE QUALITY > Semen Analysis (Motility) > After Harvest' => $this->sa_motility_ah,
            'OOCYTE QUALITY > Semen Analysis (Grade) > Native' => $this->sa_grade_native,
            'OOCYTE QUALITY > Semen Analysis (Grade) > After Harvest' => $this->sa_grade_ah,
            'OOCYTE QUALITY > Semen Analysis (Pus cells) > Native' => $this->sa_pus_cells_native,
            'OOCYTE QUALITY > Semen Analysis (Pus cells) > After Harvest' => $this->sa_pus_cells_ah,
            'OOCYTE QUALITY > Semen Analysis (Immature cells) > Native' => $this->sa_immature_cells_native,
            'OOCYTE QUALITY > Semen Analysis (Immature cells) > After Harvest' => $this->sa_immature_cells_ah,
            'OOCYTE QUALITY > Semen Analysis (Agglutination) > Native' => $this->sa_agglutination_native,
            'OOCYTE QUALITY > Semen Analysis (Agglutination) > After Harvest' => $this->sa_agglutination_ah,
            'OOCYTE QUALITY > Semen Analysis (Granular Debris) > Native' => $this->sa_granular_debris_native,
            'OOCYTE QUALITY > Semen Analysis (Granular Debris) > After Harvest' => $this->sa_granular_debris_ah,
            'OOCYTE QUALITY > Semen Analysis (Insemination Time) > Native' => $this->sa_insemination_time_native,
            'OOCYTE QUALITY > Semen Analysis (Insemination Time) > After Harvest' => $this->sa_insemination_time_ah,
            'OOCYTE QUALITY > Hrs. (I)' => $this->sa_hrs_1,
            'OOCYTE QUALITY > Post Insemination (I)' => $this->sa_posti_1,
            'OOCYTE QUALITY > No.2 PN (I)' => $this->sa_no2pn_1,
            'OOCYTE QUALITY > 2PN (I)' => $this->sa_2pn_1,
            'OOCYTE QUALITY > >2PN (I)' => $this->sa_max2pn_1,
            'OOCYTE QUALITY > Hrs. (II)' => $this->sa_hrs_2,
            'OOCYTE QUALITY > Post Insemination (II)' => $this->sa_posti_2,
            'OOCYTE QUALITY > No.2 PN (II)' => $this->sa_no2pn_2,
            'OOCYTE QUALITY > 2PN (II)' => $this->sa_2pn_2,
            'OOCYTE QUALITY > >2PN (II)' => $this->sa_max2pn_2,
            'OOCYTE QUALITY > Date (8) > Used (No.)' => $this->sa_used_no_8,
            'OOCYTE QUALITY > Date (8) > Used (Grade)' => $this->sa_used_grade_8,
            'OOCYTE QUALITY > Date (8) > Frozen (No.)' => $this->sa_frozen_no_8,
            'OOCYTE QUALITY > Date (8) > Frozen (Grade)' => $this->sa_frozen_grade_8,
            'OOCYTE QUALITY > Date (8) > Culture in M3 (No.)' => $this->sa_m3_no_8,
            'OOCYTE QUALITY > Date (8) > Culture in M3 (Grade)' => $this->sa_m3_grade_8,
            'OOCYTE QUALITY > Date (4) > Used (No.)' => $this->sa_used_no_4,
            'OOCYTE QUALITY > Date (4) > Used (Grade)' => $this->sa_used_grade_4,
            'OOCYTE QUALITY > Date (4) > Frozen (No.)' => $this->sa_frozen_no_4,
            'OOCYTE QUALITY > Date (4) > Frozen (Grade)' => $this->sa_frozen_grade_4,
            'OOCYTE QUALITY > Date (4) > Culture in M3 (No.)' => $this->sa_m3_no_4,
            'OOCYTE QUALITY > Date (4) > Culture in M3 (Grade)' => $this->sa_m3_grade_4,
            'OOCYTE QUALITY > Date (2) > Used (No.)' => $this->sa_used_no_2,
            'OOCYTE QUALITY > Date (2) > Used (Grade)' => $this->sa_used_grade_2,
            'OOCYTE QUALITY > Date (2) > Frozen (No.)' => $this->sa_frozen_no_2,
            'OOCYTE QUALITY > Date (2) > Frozen (Grade)' => $this->sa_frozen_grade_2,
            'OOCYTE QUALITY > Date (2) > Culture in M3 (No.)' => $this->sa_m3_no_2,
            'OOCYTE QUALITY > Date (2) > Culture in M3 (Grade)' => $this->sa_m3_grade_2,
            'OOCYTE QUALITY > Date (2PN) > Used (No.)' => $this->sa_used_no_2pn,
            'OOCYTE QUALITY > Date (2PN) > Used (Grade)' => $this->sa_used_grade_2pn,
            'OOCYTE QUALITY > Date (2PN) > Frozen (No.)' => $this->sa_frozen_no_2pn,
            'OOCYTE QUALITY > Date (2PN) > Frozen (Grade)' => $this->sa_frozen_grade_2pn,
            'OOCYTE QUALITY > Date (2PN) > Culture in M3 (No.)' => $this->sa_m3_no_2pn,
            'OOCYTE QUALITY > Date (2PN) > Culture in M3 (Grade)' => $this->sa_m3_grade_2pn,
            'OOCYTE QUALITY > Date (Total) > Used (No.)' => $this->sa_used_no_total,
            'OOCYTE QUALITY > Date (Total) > Used (Grade)' => $this->sa_used_grade_total,
            'OOCYTE QUALITY > Date (Total) > Frozen (No.)' => $this->sa_frozen_no_total,
            'OOCYTE QUALITY > Date (Total) > Frozen (Grade)' => $this->sa_frozen_grade_total,
            'OOCYTE QUALITY > Date (Total) > Culture in M3 (No.)' => $this->sa_m3_no_total,
            'OOCYTE QUALITY > Date (Total) > Culture in M3 (Grade)' => $this->sa_m3_grade_total,
            'Embryo Transfer > Date of ET' => $this->et_date_of_et,
            'Embryo Transfer > Time of ET' => $this->et_time_of_et,
            'Embryo Transfer > Endometrium Thickness' => $this->et_endometrium_t,
            'Embryo Transfer > ET Cathetar used' => $this->et_cathetar,
            'Embryo Transfer > Total No. of Embryo Transfer & Stage' => $this->et_transfer_stage,
            'Embryo Transfer > Embryo Transfer' => ucfirst(str_replace('_', ' ', $this->et_embryo_transfer)),
            'Blastocyst Transfer > Date of ET' => $this->bt_date_of_et,
            'Blastocyst Transfer > Time of ET' => $this->bt_time_of_et,
            'Blastocyst Transfer > Endometrium Thickness' => $this->bt_endometrium_t,
            'Blastocyst Transfer > BT Cathetar used' => $this->bt_cathetar,
            'Blastocyst Transfer > Total No. of Blastocyst Transfer & Stage' => $this->bt_transfer_stage,
            'Blastocyst Transfer > Blastocyst Transfer' => ucfirst(str_replace('_', ' ', $this->bt_embryo_transfer)),
            'Frozen > No. of Embryo frozen & stage' => $this->frozen_stage,
            'Frozen > No. of Blastocyst frozen' => $this->frozen_blastocyst,
            'Frozen > Date & Time of Embryo freezing' => $this->frozen_embryo_datetime,
            'Frozen > Date & Time of Blastocyst freezing' => $this->frozen_blastocyst_datetime,
            'Frozen > No. of Straws used' => $this->frozen_straws,
            'Frozen > Colour Code & Mark' => $this->frozen_mark,
            'Frozen > Plastic Con. Colour' => $this->frozen_plastic_colour,
            'Frozen > Con. No. in L.N2' => $this->frozen_ln2,
            'Thawing > Date of ET of thow Embryo' => $this->thawing_date_of_et,
            'Thawing > Time of ET' => $this->thawing_time_of_et,
            'Thawing > Endometrium Thickness' => $this->thawing_endometrium_t,
            'Thawing > ET Cathetar used' => $this->thawing_cathetar,
            'Thawing > Total No. of Embryo Transfer & Stage' => $this->thawing_transfer_stage,
            'Thawing > Embryo Transfer' => ucfirst(str_replace('_', ' ', $this->thawing_embryo_transfer)),
            'OI > Trial Transfer on' => $this->result_tton,
            'OI > By' => $this->result_by,
            'OI > Remarks' => $this->result_remarks,
            'OI > OC Start' => $this->result_oc_start,
            'OI > Stop' => $this->result_stop,
            'OI > LMP' => $this->result_lmp,
            'OI > Stm Start' => $this->result_stm_start,
            'OI > Protocol' => $this->result_protocol,
            'OI > # (1) > Date' => $this->result_date_1,
            'OI > # (1) > Cyc Day' => $this->result_cyc_day_1,
            'OI > # (1) > Sym Day' => $this->result_stm_day_1,
            'OI > # (1) > End' => $this->result_end_1,
            'OI > # (1) > R Ovary AFC' => $this->result_rafc_1,
            'OI > # (1) > L Ovary AFC' => $this->result_lafc_1,
            'OI > # (1) > Stimulation' => $this->result_stimulation_1,
            'OI > # (1) > Misc.' => $this->result_misc_1,
            'OI > # (2) > Date' => $this->result_date_2,
            'OI > # (2) > Cyc Day' => $this->result_cyc_day_2,
            'OI > # (2) > Sym Day' => $this->result_stm_day_2,
            'OI > # (2) > End' => $this->result_end_2,
            'OI > # (2) > R Ovary AFC' => $this->result_rafc_2,
            'OI > # (2) > L Ovary AFC' => $this->result_lafc_2,
            'OI > # (2) > Stimulation' => $this->result_stimulation_2,
            'OI > # (2) > Misc.' => $this->result_misc_2,
            'OI > # (3) > Date' => $this->result_date_3,
            'OI > # (3) > Cyc Day' => $this->result_cyc_day_3,
            'OI > # (3) > Sym Day' => $this->result_stm_day_3,
            'OI > # (3) > End' => $this->result_end_3,
            'OI > # (3) > R Ovary AFC' => $this->result_rafc_3,
            'OI > # (3) > L Ovary AFC' => $this->result_lafc_3,
            'OI > # (3) > Stimulation' => $this->result_stimulation_3,
            'OI > # (3) > Misc.' => $this->result_misc_3,
            'OI > # (4) > Date' => $this->result_date_4,
            'OI > # (4) > Cyc Day' => $this->result_cyc_day_4,
            'OI > # (4) > Sym Day' => $this->result_stm_day_4,
            'OI > # (4) > End' => $this->result_end_4,
            'OI > # (4) > R Ovary AFC' => $this->result_rafc_4,
            'OI > # (4) > L Ovary AFC' => $this->result_lafc_4,
            'OI > # (4) > Stimulation' => $this->result_stimulation_4,
            'OI > # (4) > Misc.' => $this->result_misc_4,
            'OI > # (5) > Date' => $this->result_date_5,
            'OI > # (5) > Cyc Day' => $this->result_cyc_day_5,
            'OI > # (5) > Sym Day' => $this->result_stm_day_5,
            'OI > # (5) > End' => $this->result_end_5,
            'OI > # (5) > R Ovary AFC' => $this->result_rafc_5,
            'OI > # (5) > L Ovary AFC' => $this->result_lafc_5,
            'OI > # (5) > Stimulation' => $this->result_stimulation_5,
            'OI > # (5) > Misc.' => $this->result_misc_5,
            'OI > # (6) > Date' => $this->result_date_6,
            'OI > # (6) > Cyc Day' => $this->result_cyc_day_6,
            'OI > # (6) > Sym Day' => $this->result_stm_day_6,
            'OI > # (6) > End' => $this->result_end_6,
            'OI > # (6) > R Ovary AFC' => $this->result_rafc_6,
            'OI > # (6) > L Ovary AFC' => $this->result_lafc_6,
            'OI > # (6) > Stimulation' => $this->result_stimulation_6,
            'OI > # (6) > Misc.' => $this->result_misc_6,
            'OI > # (7) > Date' => $this->result_date_7,
            'OI > # (7) > Cyc Day' => $this->result_cyc_day_7,
            'OI > # (7) > Sym Day' => $this->result_stm_day_7,
            'OI > # (7) > End' => $this->result_end_7,
            'OI > # (7) > R Ovary AFC' => $this->result_rafc_7,
            'OI > # (7) > L Ovary AFC' => $this->result_lafc_7,
            'OI > # (7) > Stimulation' => $this->result_stimulation_7,
            'OI > # (7) > Misc.' => $this->result_misc_7,
            'OI > # (8) > Date' => $this->result_date_8,
            'OI > # (8) > Cyc Day' => $this->result_cyc_day_8,
            'OI > # (8) > Sym Day' => $this->result_stm_day_8,
            'OI > # (8) > End' => $this->result_end_8,
            'OI > # (8) > R Ovary AFC' => $this->result_rafc_8,
            'OI > # (8) > L Ovary AFC' => $this->result_lafc_8,
            'OI > # (8) > Stimulation' => $this->result_stimulation_8,
            'OI > # (8) > Misc.' => $this->result_misc_8,
            'OI > # (9) > Date' => $this->result_date_9,
            'OI > # (9) > Cyc Day' => $this->result_cyc_day_9,
            'OI > # (9) > Sym Day' => $this->result_stm_day_9,
            'OI > # (9) > End' => $this->result_end_9,
            'OI > # (9) > R Ovary AFC' => $this->result_rafc_9,
            'OI > # (9) > L Ovary AFC' => $this->result_lafc_9,
            'OI > # (9) > Stimulation' => $this->result_stimulation_9,
            'OI > # (9) > Misc.' => $this->result_misc_9,
            'OI > # (10) > Date' => $this->result_date_10,
            'OI > # (10) > Cyc Day' => $this->result_cyc_day_10,
            'OI > # (10) > Sym Day' => $this->result_stm_day_10,
            'OI > # (10) > End' => $this->result_end_10,
            'OI > # (10) > R Ovary AFC' => $this->result_rafc_10,
            'OI > # (10) > L Ovary AFC' => $this->result_lafc_10,
            'OI > # (10) > Stimulation' => $this->result_stimulation_10,
            'OI > # (10) > Misc.' => $this->result_misc_10,
            'OI > # (11) > Date' => $this->result_date_11,
            'OI > # (11) > Cyc Day' => $this->result_cyc_day_11,
            'OI > # (11) > Sym Day' => $this->result_stm_day_11,
            'OI > # (11) > End' => $this->result_end_11,
            'OI > # (11) > R Ovary AFC' => $this->result_rafc_11,
            'OI > # (11) > L Ovary AFC' => $this->result_lafc_11,
            'OI > # (11) > Stimulation' => $this->result_stimulation_11,
            'OI > # (11) > Misc.' => $this->result_misc_11,
            'OI > # (12) > Date' => $this->result_date_12,
            'OI > # (12) > Cyc Day' => $this->result_cyc_day_12,
            'OI > # (12) > Sym Day' => $this->result_stm_day_12,
            'OI > # (12) > End' => $this->result_end_12,
            'OI > # (12) > R Ovary AFC' => $this->result_rafc_12,
            'OI > # (12) > L Ovary AFC' => $this->result_lafc_12,
            'OI > # (12) > Stimulation' => $this->result_stimulation_12,
            'OI > # (12) > Misc.' => $this->result_misc_12,
            'OI > # (13) > Date' => $this->result_date_13,
            'OI > # (13) > Cyc Day' => $this->result_cyc_day_13,
            'OI > # (13) > Sym Day' => $this->result_stm_day_13,
            'OI > # (13) > End' => $this->result_end_13,
            'OI > # (13) > R Ovary AFC' => $this->result_rafc_13,
            'OI > # (13) > L Ovary AFC' => $this->result_lafc_13,
            'OI > # (13) > Stimulation' => $this->result_stimulation_13,
            'OI > # (13) > Misc.' => $this->result_misc_13,
            'OI > # (14) > Date' => $this->result_date_14,
            'OI > # (14) > Cyc Day' => $this->result_cyc_day_14,
            'OI > # (14) > Sym Day' => $this->result_stm_day_14,
            'OI > # (14) > End' => $this->result_end_14,
            'OI > # (14) > R Ovary AFC' => $this->result_rafc_14,
            'OI > # (14) > L Ovary AFC' => $this->result_lafc_14,
            'OI > # (14) > Stimulation' => $this->result_stimulation_14,
            'OI > # (14) > Misc.' => $this->result_misc_14,
            'OI > # (15) > Date' => $this->result_date_15,
            'OI > # (15) > Cyc Day' => $this->result_cyc_day_15,
            'OI > # (15) > Sym Day' => $this->result_stm_day_15,
            'OI > # (15) > End' => $this->result_end_15,
            'OI > # (15) > R Ovary AFC' => $this->result_rafc_15,
            'OI > # (15) > L Ovary AFC' => $this->result_lafc_15,
            'OI > # (15) > Stimulation' => $this->result_stimulation_15,
            'OI > # (15) > Misc.' => $this->result_misc_15,
            'OI > # (16) > Date' => $this->result_date_16,
            'OI > # (16) > Cyc Day' => $this->result_cyc_day_16,
            'OI > # (16) > Sym Day' => $this->result_stm_day_16,
            'OI > # (16) > End' => $this->result_end_16,
            'OI > # (16) > R Ovary AFC' => $this->result_rafc_16,
            'OI > # (16) > L Ovary AFC' => $this->result_lafc_16,
            'OI > # (16) > Stimulation' => $this->result_stimulation_16,
            'OI > # (16) > Misc.' => $this->result_misc_16,
            'OI > HCG' => $this->result_hcg,
            'OI > Date/Time (I)' => $this->result_datetime1,
            'OI > OPU' => $this->result_opu,
            'OI > Date/Time (II)' => $this->result_datetime2,
            'OI > Total COC' => $this->result_coc,
            'OI > GV' => $this->result_gv,
            'OI > M1' => $this->result_m1,
            'OI > M2' => $this->result_m2,
            'OI > IVF' => $this->result_ivf,
            'OI > ICSI' => $this->result_icsi,
            'OI > ET (I)' => $this->result_et1,
            'OI > Cryo' => $this->result_cryo,
            'OI > ET (II)' => $this->result_et2,
            'OI > Date/Time (III)' => $this->result_datetime3,
            'OI > Details' => ucfirst($this->result_details),
            'OI > VP/DBG/GST' => $this->result_vp,
            'OI > E/U Date' => $this->result_eudate,
            'OI > B-HCG' => $this->result_bhcg,
            'OI > Semen Cryo' => $this->result_semen_cryo,
            'OI > Antibiotic for husband' => $this->result_afh,
            'OI > Antifungal' => $this->result_antifungal
        ];
    }
}
